tittle: Aitech
#logo
discrimination: FIX PROGRAME SELL 
#SHOW_DOWNLOADS: THRUE
THEME: ninmal

### if : (Rating >= 5-Stars) {open (StoreEntry/InAppReview) to get rating} else {(Ask for Mail Feedback) or (Trigger an event)} 
          BetterRateDialog betterRateDialog = new BetterRateDialog(this, Aitechvest@gmail.com);
        betterRateDialog.setRateText(GOOD QUALITY ASSISATNCE)
                .setTitle(LYNQUATIQ)
                .setForceMode(false) /*Open store entry without asking the User*/
                .setUpperBound(3) /*If Rating >= 3 open (StoreEntry/InAppRating)*/
                .setNegativeReviewListener(this) /*Custom Listener which overrides Mail Intent*/
                .setReviewListener(this) /*Custom ReviewListener*/
                .setGooglePlayInAppReviewMode(true) /*Open InAppReview for Google Play Apps*/
                .showAfter(ShowMode.LAUNCH_TIMES, 2); /*The condition when to display it*/
# follow and subscribe 👋

## moreinfo

[![My Skills](https://skillicons.dev/icons?i=html,css,js,ts,react,redux,nodejs,express,mongo,postgres,redis,bash,git,githubactions,docker,kubernetes,aws,heroku,postman,neovim,nginx,python,linux&perline=6)]()

## contact

- [youtube](https://www.youtube.com/@audiovestrecords) 
  Also Available on [facebook]
- [instergram]
- [whatsapp](27715151309)
